version: "3.9"

x-base: &base-market
  image: market
  build:
    context: .
    target: development

services:
  django-server:
    <<: *base-market
    ports:
      - "8000:8000"
    volumes:
      - ./media:/media
